# Description: Arquivo de configuração do Docker Compose


services: # Define os serviços que serão executados
  server: # Define o serviço server
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - minha-rede

  client-station-1: 
    build: ./client-station
    networks:
      - minha-rede
    depends_on:
      - server
    environment:
       - STATION_ID=1

  client-station-2:
    build: ./client-station
    networks:
      - minha-rede
    depends_on:
      - server
    environment:
       - STATION_ID=2

  client-station-3:
    build: ./client-station
    networks:
      - minha-rede
    depends_on:
      - server
    environment:
       - STATION_ID=3

  client-station-4:
    build: ./client-station
    networks:
      - minha-rede
    depends_on:
      - server
    environment:
       - STATION_ID=4

  client-station-5:
    build: ./client-station
    networks:
      - minha-rede
    depends_on:
      - server
    environment:
       - STATION_ID=5

  client-car:
    build: ./client-car
    networks:
      - minha-rede
    depends_on:
      - server
    deploy:
      replicas: 3 # Define o número de réplicas do serviço client

networks: # Define as redes que serão utilizadas
  minha-rede:
    driver: bridge
