# Description: Arquivo de configuração do Docker Compose  
version: "2.29.1"

services:
  station:  # Nome mais apropriado para o posto
    build: ./client-station
    ports:
      - "8080:8080"
    networks:
      - minha-rede

  client:
    build: ./client-car
    networks:
      - minha-rede
    depends_on:
      - station

networks: # Define as redes que serão utilizadas
  minha-rede:
    driver: bridge
